---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rhel9-amd64-guest
  namespace: openshift-virtualization-os-images
  labels:
    app.kubernetes.io/name: rhel9-amd64-guest
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.redhat.io/rhel9/rhel-guest-image:latest
      importPolicy:
        scheduled: true
        importMode: PreserveOriginal
      referencePolicy:
        type: Source
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  name: rhel9-amd64-image-cron
  namespace: openshift-virtualization-os-images
  labels:
    app.kubernetes.io/name: rhel9-amd64-datasource
spec:
  managedDataSource: rhel9-amd64
  schedule: "0 */12 * * *"
  template:
    spec:
      source:
        registry:
          imageStream: rhel9-amd64-guest
          pullMethod: node
      storage:
        resources:
          requests:
            storage: 30Gi
  garbageCollect: Outdated
