apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  name: rhel9-amd64-image-cron
  namespace: openshift-virtualization-os-images
  labels:
    app.kubernetes.io/component: templating
    app.kubernetes.io/managed-by: custom
    app.kubernetes.io/name: data-sources
spec:
  managedDataSource: rhel9-amd64
  schedule: "0 */12 * * *"
  template:
    spec:
      source:
        registry:
          imageStream: rhel9-amd64-guest
          pullMethod: node
      storage:
        resources:
          requests:
            storage: 30Gi
  garbageCollect: Outdated
