apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: poc-cluster-workers
  namespace: clusters
  annotations:
    # Configure x86_64 architecture with SecureBoot and SMM for UEFI boot
    hypershift.openshift.io/kubevirt-vm-jsonpatch: |
      [
        {"op": "replace", "path": "/spec/template/spec/architecture", "value": "amd64"},
        {"op": "add", "path": "/spec/template/spec/domain/firmware", "value": {"bootloader": {"efi": {"secureBoot": true}}}},
        {"op": "add", "path": "/spec/template/spec/domain/features", "value": {"smm": {"enabled": true}}}
      ]
spec:
  clusterName: poc-cluster
  replicas: 2
  arch: amd64
  management:
    autoRepair: true
    replace:
      strategy: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    upgradeType: Replace
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.18.30-multi
  platform:
    type: KubeVirt
    kubevirt:
      compute:
        cores: 8
        memory: 32Gi
      rootVolume:
        persistent:
          size: 100Gi
          storageClass: gp3-csi
        type: Persistent
      nodeSelector:
        kubernetes.io/arch: amd64
