---
# ServiceAccount with IRSA annotation for cross-account AWS access
# The IAM role ARN will be in your personal AWS account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: "arn:aws:iam::067777428281:role/rosa-external-secrets-role"
