---
# ArgoCD Application: GitHub Actions Runner Controller (ARC)
# Deploys self-hosted runners for GitHub Actions workflows
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: openshift-gitops
  annotations:
    # Deploy after external-secrets operator is ready (sync-wave 1)
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: hypershift-platform
  source:
    repoURL: https://github.com/kylape/hypershift-platform-gitops.git
    targetRevision: main
    path: platform/arc
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
