---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-namespace
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: hypershift-platform
  source:
    repoURL: https://github.com/kylape/hypershift-platform-gitops.git
    targetRevision: main
    path: platform
    directory:
      include: clusters-namespace.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
