---
# ArgoCD Application: External Secrets Operator
# Syncs secrets from AWS Secrets Manager to Kubernetes
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-gitops
  annotations:
    # Deploy early - other apps depend on secrets
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: hypershift-platform
  source:
    repoURL: https://github.com/kylape/hypershift-platform-gitops.git
    targetRevision: main
    path: platform/external-secrets
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
