---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hypershift-crds
  namespace: openshift-gitops
spec:
  project: hypershift-platform
  source:
    repoURL: https://github.com/kylape/hypershift-platform-gitops.git
    targetRevision: main
    path: platform/hypershift
    directory:
      include: crds.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
