---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackrox-central
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: hypershift-platform
  source:
    repoURL: https://github.com/kylape/hypershift-platform-gitops.git
    targetRevision: main
    path: platform/stackrox-operator
    directory:
      include: central.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
