apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
spec:
  availabilityConfig: High
  overrides:
    components:
      - name: hypershift
        enabled: true
      - name: hypershift-local-hosting
        enabled: true
