apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml

# Default image - can be overridden via ApplicationSet kustomize.images
images:
  - name: quay.io/stackrox-io/stackrox-operator
    newName: quay.io/stackrox-io/stackrox-operator
    newTag: 4.10.0-rc.4
