apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/kubevirt-hyperconverged.openshift-cnv: ""
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: kubevirt-hyperconverged
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: kubevirt-hyperconverged-operator.v4.18.23
    catalogHealth:
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: certified-operators
        namespace: openshift-marketplace
      healthy: true
      lastUpdated: "2026-01-21T18:26:22Z"
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: community-operators
        namespace: openshift-marketplace
      healthy: true
      lastUpdated: "2026-01-21T18:26:22Z"
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-marketplace
        namespace: openshift-marketplace
      healthy: true
      lastUpdated: "2026-01-21T18:26:22Z"
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-operators
        namespace: openshift-marketplace
      healthy: true
      lastUpdated: "2026-01-21T18:26:22Z"
    conditions:
    - lastTransitionTime: "2026-01-21T18:26:22Z"
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      type: CatalogSourcesUnhealthy
    currentCSV: kubevirt-hyperconverged-operator.v4.18.23
    installPlanGeneration: 1
    installPlanRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: InstallPlan
      name: install-6pdvx
      namespace: openshift-cnv
    installedCSV: kubevirt-hyperconverged-operator.v4.18.23
    installplan:
      apiVersion: operators.coreos.com/v1alpha1
      kind: InstallPlan
      name: install-6pdvx
    lastUpdated: "2026-01-21T18:26:57Z"
    state: AtLatestKnown
kind: List
metadata:
