---
# Simple Service Account for DinD runners (no special permissions needed)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stackrox-runners-dind
  namespace: arc-runners
---
# AMD64 Runner Pool - DinD mode
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: stackrox-runners-amd64
  namespace: arc-runners
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    app.kubernetes.io/name: stackrox-runners-amd64
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: "0.9.3"
    actions.github.com/scale-set-name: stackrox-runners-amd64
    actions.github.com/scale-set-namespace: arc-runners
spec:
  githubConfigUrl: https://github.com/kylape/stackrox
  githubConfigSecret: github-app-secret
  maxRunners: 20
  minRunners: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: stackrox-runners-dind
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
      - name: init-dind-externals
        image: ghcr.io/actions/actions-runner:latest
        command: ["cp"]
        args: ["-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
          - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
            value: "120"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --host=unix:///var/run/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
          - name: dind-externals
            mountPath: /home/runner/externals
          - name: dind-data
            mountPath: /var/lib/docker
      volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: lvms-nvme
      - name: dind-data
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: lvms-nvme
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
---
# ARM64 Runner Pool - DinD mode
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: stackrox-runners-arm64
  namespace: arc-runners
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    app.kubernetes.io/name: stackrox-runners-arm64
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: "0.9.3"
    actions.github.com/scale-set-name: stackrox-runners-arm64
    actions.github.com/scale-set-namespace: arc-runners
spec:
  githubConfigUrl: https://github.com/kylape/stackrox
  githubConfigSecret: github-app-secret
  maxRunners: 20
  minRunners: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: stackrox-runners-dind
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
      - name: init-dind-externals
        image: ghcr.io/actions/actions-runner:latest
        command: ["cp"]
        args: ["-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
          - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
            value: "120"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --host=unix:///var/run/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
          - name: dind-externals
            mountPath: /home/runner/externals
          - name: dind-data
            mountPath: /var/lib/docker
      volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: lvms-nvme
      - name: dind-data
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: lvms-nvme
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
