---
# Source: gha-runner-scale-set/templates/no_permission_serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stackrox-runners-gha-rs-no-permission
  namespace: arc-runners
  labels:
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: stackrox-runners
    app.kubernetes.io/instance: stackrox-runners
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: stackrox-runners
    actions.github.com/scale-set-namespace: arc-runners
  finalizers:
    - actions.github.com/cleanup-protection
---
# Source: gha-runner-scale-set/templates/manager_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stackrox-runners-gha-rs-manager
  namespace: arc-runners
  labels:
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: stackrox-runners
    app.kubernetes.io/instance: stackrox-runners
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: stackrox-runners
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/component: manager-role
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
# Source: gha-runner-scale-set/templates/manager_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-runners-gha-rs-manager
  namespace: arc-runners
  labels:
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: stackrox-runners
    app.kubernetes.io/instance: stackrox-runners
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: stackrox-runners
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/component: manager-role-binding
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stackrox-runners-gha-rs-manager
subjects:
- kind: ServiceAccount
  name:
    arc-controller-gha-rs-controller
  namespace:
    arc-systems
---
# AMD64 Runner Pool - No DinD, uses Kubernetes mode for containers
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: stackrox-runners-amd64
  namespace: arc-runners
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: stackrox-runners-amd64
    app.kubernetes.io/instance: stackrox-runners-amd64
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: stackrox-runners-amd64
    actions.github.com/scale-set-namespace: arc-runners
  annotations:
    actions.github.com/cleanup-manager-role-binding: stackrox-runners-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: stackrox-runners-gha-rs-manager
    actions.github.com/cleanup-no-permission-service-account-name: stackrox-runners-gha-rs-no-permission
spec:
  githubConfigUrl: https://github.com/kylape/stackrox
  githubConfigSecret: github-app-secret
  maxRunners: 10
  minRunners: 0
  containerMode:
    type: kubernetes
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: topolvm-provisioner
      resources:
        requests:
          storage: 10Gi

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: stackrox-runners-gha-rs-no-permission
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: runner
        command:
          - /home/runner/run.sh
        image: ghcr.io/actions/actions-runner:latest
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
      volumes:
      - name: work
        emptyDir: {}
---
# ARM64 Runner Pool - No DinD, uses Kubernetes mode for containers
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: stackrox-runners-arm64
  namespace: arc-runners
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.9.3
    app.kubernetes.io/name: stackrox-runners-arm64
    app.kubernetes.io/instance: stackrox-runners-arm64
    app.kubernetes.io/version: "0.9.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: stackrox-runners-arm64
    actions.github.com/scale-set-namespace: arc-runners
  annotations:
    actions.github.com/cleanup-manager-role-binding: stackrox-runners-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: stackrox-runners-gha-rs-manager
    actions.github.com/cleanup-no-permission-service-account-name: stackrox-runners-gha-rs-no-permission
spec:
  githubConfigUrl: https://github.com/kylape/stackrox
  githubConfigSecret: github-app-secret
  maxRunners: 10
  minRunners: 0
  containerMode:
    type: kubernetes
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: topolvm-provisioner
      resources:
        requests:
          storage: 10Gi

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: stackrox-runners-gha-rs-no-permission
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: runner
        command:
          - /home/runner/run.sh
        image: ghcr.io/actions/actions-runner:latest
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
      volumes:
      - name: work
        emptyDir: {}
