---
# ExternalSecret that fetches GitHub App credentials from AWS Secrets Manager
# The secret in AWS should be named: arc/github-app
# And contain keys: github_app_id, github_app_installation_id, github_app_private_key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-secret
  namespace: arc-runners
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: github-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: arc/github-app
