apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel-9-acs-test
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhel-9-acs-test
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '32212254720'
          storageClassName: gp3-csi
  instancetype:
    name: u1.medium
  preference:
    name: rhel.9
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: rhel-9-acs-test
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - default
                - name: cloud-user
                  groups: wheel
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
                  lock_passwd: false
          name: cloudinitdisk
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              qemuGuestAgent:
                users:
                  - cloud-user
            source:
              secret:
                secretName: klape-public-ssh
