apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel-8-acs-test
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhel-8-acs-test
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '32212254720'
          storageClassName: gp3-csi
  instancetype:
    name: u1.medium
  preference:
    name: rhel.8
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: rhel-8-acs-test
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: cloud-user
                  gecos: Cloud User
                  groups: wheel
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
                  homedir: /home/cloud-user
              runcmd:
                - mkdir -p /home/cloud-user/.ssh
                - chmod 700 /home/cloud-user/.ssh
                - touch /home/cloud-user/.ssh/authorized_keys
                - chmod 600 /home/cloud-user/.ssh/authorized_keys
                - chown -R cloud-user:cloud-user /home/cloud-user/.ssh
          name: cloudinitdisk
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              qemuGuestAgent:
                users:
                  - cloud-user
            source:
              secret:
                secretName: klape-public-ssh
