apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: nvme-lvmcluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storage:
    deviceClasses:
      - name: nvme
        default: true
        fstype: xfs
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/instance-type
                  operator: In
                  values:
                    - m7gd.metal
        deviceSelector:
          # Auto-discover NVMe instance storage disks (non-partitioned)
          # LVMS will only use disks that are:
          # - Not mounted
          # - Have no partitions
          # - Have no LVM signature
          # - Have no filesystem
          optionalPaths:
            - /dev/nvme0n1
            - /dev/nvme1n1
            - /dev/nvme3n1
            - /dev/nvme4n1
        thinPoolConfig:
          name: thin-pool-nvme
          overprovisionRatio: 10
          sizePercent: 90
