apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lvms-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - openshift-storage
