apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - openshift-local-storage
