apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: central-prometheus-k8s
    namespace: stackrox
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: central-sts-config-reader
    namespace: stackrox
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - gcp-cloud-credentials
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: config-controller
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: config-controller-manager-role
    namespace: stackrox
  rules:
  - apiGroups:
    - config.stackrox.io
    resources:
    - securitypolicies
    - securitypolicies/status
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-secured-cluster-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: sensor
      app.kubernetes.io/instance: stackrox-secured-cluster-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-secured-cluster-services
      app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
      auto-upgrade.stackrox.io/component: sensor
      helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
    name: edit
    namespace: stackrox
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
    - deletecollection
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-secured-cluster-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/instance: stackrox-secured-cluster-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-secured-cluster-services
      app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
      auto-upgrade.stackrox.io/component: sensor
      helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
    name: secured-cluster-prometheus-k8s
    namespace: stackrox
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: stackrox-central-diagnostics
    namespace: stackrox
  rules:
  - apiGroups:
    - '*'
    resources:
    - deployments
    - daemonsets
    - replicasets
    - configmaps
    - services
    - pods
    - pods/log
    - events
    - namespaces
    verbs:
    - get
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: use-central-db-scc
    namespace: stackrox
  rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - nonroot-v2
    resources:
    - securitycontextconstraints
    verbs:
    - use
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: use-central-scc
    namespace: stackrox
  rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - nonroot-v2
    resources:
    - securitycontextconstraints
    verbs:
    - use
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-secured-cluster-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: collector
      app.kubernetes.io/instance: stackrox-secured-cluster-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-secured-cluster-services
      app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
      auto-upgrade.stackrox.io/component: sensor
      helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
    name: use-privileged-scc
    namespace: stackrox
  rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - privileged
    resources:
    - securitycontextconstraints
    verbs:
    - use
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: scanner-v4
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: use-scanner-v4-scc
    namespace: stackrox
  rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - nonroot-v2
    - restricted-v2
    resources:
    - securitycontextconstraints
    verbs:
    - use
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-secured-cluster-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: admission-control
      app.kubernetes.io/instance: stackrox-secured-cluster-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-secured-cluster-services
      app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
      auto-upgrade.stackrox.io/component: sensor
      helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
    name: watch-config
    namespace: stackrox
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
kind: List
metadata:
