apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-secured-cluster-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: admission-control
      app.kubernetes.io/instance: stackrox-secured-cluster-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-secured-cluster-services
      app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
      auto-upgrade.stackrox.io/component: sensor
      helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
    name: admission-control-watch-config
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: watch-config
  subjects:
  - kind: ServiceAccount
    name: admission-control
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: central-db-use-scc
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: use-central-db-scc
  subjects:
  - kind: ServiceAccount
    name: central-db
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: central-prometheus-k8s
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: central-prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: central-sts-config-reader
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: central-sts-config-reader
  subjects:
  - kind: ServiceAccount
    name: central
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: central-use-scc
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: use-central-scc
  subjects:
  - kind: ServiceAccount
    name: central
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-secured-cluster-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: collector
      app.kubernetes.io/instance: stackrox-secured-cluster-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-secured-cluster-services
      app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
      auto-upgrade.stackrox.io/component: sensor
      helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
    name: collector-use-scc
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: use-privileged-scc
  subjects:
  - kind: ServiceAccount
    name: collector
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: config-controller
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: config-controller-manager-rolebinding
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: config-controller-manager-role
  subjects:
  - kind: ServiceAccount
    name: config-controller
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: dedicated-admin-serviceaccounts-0
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: dedicated-admins-project
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:dedicated-admin
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: dedicated-admin-serviceaccounts-1
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:dedicated-admin
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: dedicated-admins-0
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: dedicated-admins-project
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: dedicated-admins
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: dedicated-admins-1
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: dedicated-admins
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: dedicated-admins-alert-routing-edit-0
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: alert-routing-edit
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: dedicated-admins
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-secured-cluster-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: sensor
      app.kubernetes.io/instance: stackrox-secured-cluster-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-secured-cluster-services
      app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
      auto-upgrade.stackrox.io/component: sensor
      helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
    name: manage-namespace
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: edit
  subjects:
  - kind: ServiceAccount
    name: sensor
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: scanner-v4
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: scanner-v4-use-scc
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: use-scanner-v4-scc
  subjects:
  - kind: ServiceAccount
    name: scanner-v4
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-secured-cluster-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/instance: stackrox-secured-cluster-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-secured-cluster-services
      app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
      auto-upgrade.stackrox.io/component: sensor
      helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
    name: secured-cluster-prometheus-k8s
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: secured-cluster-prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      email: support@stackrox.com
      meta.helm.sh/release-name: stackrox-central-services
      meta.helm.sh/release-namespace: stackrox
      owner: stackrox
    labels:
      app.kubernetes.io/component: central
      app.kubernetes.io/instance: stackrox-central-services
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: stackrox
      app.kubernetes.io/part-of: stackrox-central-services
      app.kubernetes.io/version: 4.9.2
      helm.sh/chart: stackrox-central-services-400.9.2
    name: stackrox-central-diagnostics
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: stackrox-central-diagnostics
  subjects:
  - kind: ServiceAccount
    name: central
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows deploymentconfigs in this namespace to rollout
        pods in this namespace.  It is auto-managed by a controller; remove subjects
        to disable.
    name: system:deployers
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows builds in this namespace to push images to
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    name: system:image-builders
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: stackrox
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows all pods in this namespace to pull images from
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    name: system:image-pullers
    namespace: stackrox
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:stackrox
kind: List
metadata:
