apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
    auto-upgrade.stackrox.io/component: sensor
    helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
  name: stackrox:create-events
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - list
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
    auto-upgrade.stackrox.io/component: sensor
    helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
  name: stackrox:edit-compliance
rules:
- apiGroups:
  - compliance.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
    auto-upgrade.stackrox.io/component: sensor
    helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
  name: stackrox:edit-workloads
rules:
- apiGroups:
  - '*'
  resources:
  - cronjobs
  - jobs
  - daemonsets
  - deployments
  - deployments/scale
  - deploymentconfigs
  - pods
  - replicasets
  - replicationcontrollers
  - services
  - statefulsets
  verbs:
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
    auto-upgrade.stackrox.io/component: sensor
    helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
  name: stackrox:network-policies
rules:
- apiGroups:
  - networking.k8s.io
  - extensions
  resources:
  - networkpolicies
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
    auto-upgrade.stackrox.io/component: sensor
    helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
  name: stackrox:review-access
rules:
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
    auto-upgrade.stackrox.io/component: sensor
    helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
  name: stackrox:review-tokens
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
    auto-upgrade.stackrox.io/component: sensor
    helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
  name: stackrox:update-namespaces
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - update
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    email: support@stackrox.com
    meta.helm.sh/release-name: stackrox-secured-cluster-services
    meta.helm.sh/release-namespace: stackrox
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
    app.kubernetes.io/version: 4.10.x-851-ge00b4bc697
    auto-upgrade.stackrox.io/component: sensor
    helm.sh/chart: stackrox-secured-cluster-services-400.10.0-851-ge00b4bc697
  name: stackrox:view-cluster
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
