apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  central:
    exposure:
      route:
        enabled: true
    persistence:
      persistentVolumeClaim:
        claimName: central-db
  scanner:
    scannerComponent: Disabled
  scannerV4:
    indexer:
      scaling:
        autoScaling: Disabled
        replicas: 1
    matcher:
      scaling:
        autoScaling: Disabled
        replicas: 1
    scannerComponent: Default
  customize:
    envVars:
      - name: ROX_VIRTUAL_MACHINES
        value: "true"
